### ISSUE TITLE
Add chopsticks?

### ISSUE THREAD

**Issue by koaning** [koaning/sushigo#3]
The game currently does not support the chopsticks card due to the complexity it adds. 

Do we *really* want it or are we fine with skipping it? We could always add it later, but it may be harder.

**Comment by koaning** [comment]
Confirmed. We'll ditch the chopsticks.

**Comment by josh-marsh** [comment]
I need to add chopsticks for a project. Any recommendations on the best way to approach this?

**Comment by koaning** [comment]
Not really, I left the chopsticks out for a reason :) why is it crucial for your project?

**Comment by josh-marsh** [comment]
It's all good I figured it out. There is no pretty solution. 

My comp course has an assignment that involves writing bots for SushiGo, and the deck we are given specifies chopsticks as well as some other restrictions.

I'm currently training a Policy Gradient RL network with self-play on a modified version of your environment. Thank you so much for producing such a beautiful implementation :)

**Comment by koaning** [comment]
interesting ... is this course using my code? a while ago somebody else asked me about it.

**Comment by koaning** [comment]
if there's an open repo with results i'd love to have a peek by the way. 

this might be relevant: https://www.youtube.com/watch?v=KUvB1hqF2OA&t=166s

**Comment by josh-marsh** [comment]
We are using Haskell and are provided with a pre-built SushiGo game. Since its only a first-year course (at ANU), we are supposed to be implementing minimax and alpha-beta pruning etc. I'm doing something a bit extra, and am training a model in python with tensorflow and deploying the trained model in Haskell.

Sure, when the assignment is over I'll make an online repo!
